import { createRouter, createWebHistory } from "vue-router";
const routes = [
    {
        path: '/', component: () => import('@/components/MainContainer.vue'),
        children: [
            { path: '/', component: () => import('@/views/Introduction.vue') },
            { path: '/writingsystem', component: () => import('@/views/WritingSystem.vue') },
            { path: '/hiragana', component: () => import('@/components/Hiragana.vue') },
            { path: '/katakana', component: () => import('@/components/Katakana.vue') },
            { path: '/kanji', component: () => import('@/components/Kanji.vue') },
            { path: '/particles', component: () => import('@/views/Particles.vue') },
            { path: '/conjugations', component: () => import('@/views/Conjunctions.vue') },
            { path: '/particle_wa', component: () => import('@/components/Particles/ParticleWa.vue') },
            { path: '/particle_ga', component: () => import('@/components/Particles/ParticleGa.vue') },
            { path: '/particle_wo', component: () => import('@/components/Particles/Particle_Wo.vue') },
            { path: '/particle_ni', component: () => import('@/components/Particles/Particle_Ni.vue') },
            { path: '/particle_de', component: () => import('@/components/Particles/Particle_De.vue') },
            { path: '/particle_no', component: () => import('@/components/Particles/ParticleNo.vue') },
            { path: '/particle_e', component: () => import('@/components/Particles/Particle_E.vue') },
            { path: '/particle_to', component: () => import('@/components/Particles/Particle_To.vue') },
            { path: '/particle_mo', component: () => import('@/components/Particles/Particle_Mo.vue') },
            { path: '/particle_kara', component: () => import('@/components/Particles/Particle_kara.vue') },
            { path: '/particle_made', component: () => import('@/components/Particles/Particle_Made.vue') },
            { path: '/dictionary', component: () => import('@/components/Conjugations/Dictionary.vue') },
            { path: '/masu', component: () => import('@/components/Conjugations/Masu.vue') },
            { path: '/politenegative', component: () => import('@/components/Conjugations/PoliteNegative.vue') },
            { path: '/pastverbconjugation', component: () => import('@/components/Conjugations/PastVerbConjugation.vue') },
            { path: '/past_negative_verb_conjugation', component: () => import('@/components/Conjugations/PastNegativeVerbConjugation.vue') },
            { path: '/te_verb_conjugation', component: () => import('@/components/Conjugations/TeVerbConjugation.vue') },
            { path: '/potentialverbconjugation', component: () => import('@/components/Conjugations/PotentialVerbConjugation.vue') },
            { path: '/volitionalverbconjugation', component: () => import('@/components/Conjugations/VolitionalVerbConjugation.vue') },
            { path: '/emperativeverbconjugation', component: () => import('@/components/Conjugations/ImperativeVerbConjugation.vue') },
            { path: '/conditionalverbconjugation', component: () => import('@/components/Conjugations/ConditionalVerbConjugation.vue') },
            { path: '/passiveverbconjugation', component: () => import('@/components/Conjugations/PassiveVerbConjugation.vue') },
            { path: '/causativeverbconjugation', component: () => import('@/components/Conjugations/CausativeVerbConjugation.vue') },
            { path: '/sequentialconjuctions', component: () => import('@/components/Conjuctions/Sequential.vue') },
            { path: '/constractiveconjuctions', component: () => import('@/components/Conjuctions/Constractive.vue') },
            { path: '/cause_and_effect', component: () => import('@/components/Conjuctions/CauseandEffect.vue') },
            { path: '/condition', component: () => import('@/components/Conjuctions/Condition.vue') },
            { path: '/addition', component: () => import('@/components/Conjuctions/Addition.vue') },
            { path: '/emphasis', component: () => import('@/components/Conjuctions/Emphasis.vue') },
            { path: '/summarizing', component: () => import('@/components/Conjuctions/Summarizing.vue') },
            { path: '/flashcards', component: () => import("@/components/Practice/Flashcard.vue") },
            { path: '/translation', component: () => import("@/components/Practice/Translation.vue") },
            { path: '/reading', component: () => import("@/components/Practice/Reading.vue") },
            { path: '/listening', component: () => import("@/components/Practice/Listening.vue") },
            { path: '/filltheblank', component: () => import("@/components/Practice/FillTheBlank.vue") },
            { path: '/practice_n5', component: () => import("@/components/Practice/PracticeN5.vue") },
            { path: '/mocktest5', component: () => import("@/components/Mocktest/MocktestJLPT5.vue") },
            { path: '/numbersystem', component: () => import("@/components/Number/NumberSystem.vue") },
            { path: '/ageexpression', component: () => import("@/components/Number/AgeExpression.vue") },
            { path: '/telephonenumbers', component: () => import("@/components/Number/TelephoneNumbers.vue") },
            { path: '/tellingtime', component: () => import("@/components/Number/TellingTime.vue") },
            { path: '/calendar', component: () => import("@/components/Vocabularies/Calendar.vue") },
            { path: '/occupation', component: () => import("@/components/Vocabularies/Occupation.vue") },
            { path: '/instution', component: () => import("@/components/Vocabularies/Institution.vue") },
            { path: '/family', component: () => import("@/components/Vocabularies/Family.vue") },
            { path: '/questions', component: () => import("@/components/Questions/AskingQuestion.vue") },
            { path: '/whatquestion', component: () => import("@/components/Questions/WhatQuestion.vue") },
            { path: '/whenquestion', component: () => import("@/components/Questions/WhenQuestion.vue") },
            { path: '/whoquestion', component: () => import("@/components/Questions/WhoQuestion.vue") },
            { path: '/wherequestion', component: () => import("@/components/Questions/WhereQuestion.vue") },
            { path: '/whyquestion', component: () => import("@/components/Questions/WhyQuestion.vue") },
            { path: '/howquestion', component: () => import("@/components/Questions/HowQuestion.vue") },
        ]
    }
];

const router = createRouter({
    history: createWebHistory('/miguro/'),
    routes,
    scrollBehavior(to, from, savedPosition) {
        return { top: 0 }; // Scroll to top
    },
});

export default router;